sudo: required
dist: trusty
language: cpp
compiler:
- gcc
- clang
addons:
  apt:
    sources:
    - george-edison55/cmake-3.x
    packages:
    - cmake
    - libsdl2-dev
    - asciidoc
    - libgtest-dev
script:
    - "cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp *.a /usr/lib && cd $TRAVIS_BUILD_DIR"
    - "mkdir build && cd build && cmake ../ && make && ctest -VV && cd .."
    - "cd docs && ./build-travis.sh && cd .."
