sudo: required
os:
- linux
- osx
dist: trusty
language: cpp
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - cmake
    - libsdl2-dev
    - asciidoc
before_install:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtest; fi

before_script:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir build && cd build && cmake ../ && make && make install && cd ..; fi
script:
    - "mkdir build && cd build && cmake ../ && make && make install && cd .."
    - "cd docs && ./build-travis.sh && cd .."
