sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - cmake
      - libsdl2-dev
      - asciidoc

script:
    - mkdir build && cd build && cmake ../ && cd ..
    - .cd docs && ./build-travis.sh && cd ..
