# Copied from https://github.com/mmatyas/supermariowar/blob/master/.appveyor.yml

platform:
  - x86

build_script:
  - C:\MinGW\msys\1.0\bin\sh --login -c "
      cd /c/projects/SuperTeacher;
      mkdir build;
      cd build;
      cmake --version;
      cmake .. -G 'MSYS Makefiles';
      make VERBOSE=1;
      ctest -VV;"
