install:
  - choco install -y 7zip
  - set PATH="C:\Program Files\7-Zip";C:\MinGW\bin;%PATH%

  # Set up SFML libs
  - appveyor DownloadFile http://www.sfml-dev.org/files/SFML-2.3.2-windows-vc14-32-bit.zip
  - 7z x SFML-2.3.2-windows-vc14-32-bit.zip
  - set SFML_ROOT=%CD%\SFML-2.3.2

build_script:
  - cd C:\projects\SuperTeacher
  - mkdir build
  - cd build
  - cmake -G"Visual Studio 14 2015" ..
  - msbuild SuperTeacher.sln
  - ctest -VV
  - cd ..
